services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: river_scraper
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - '5001:5001'
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
