version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: river_scraper
    working_dir: /app
    volumes:
      - .:/app
    command: ['python', 'main.py']
